# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HumanTaskTrigger(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_workflow_request': 'StartWorkflowRequest',
        'trigger_type': 'str'
    }

    attribute_map = {
        'start_workflow_request': 'startWorkflowRequest',
        'trigger_type': 'triggerType'
    }

    def __init__(self, start_workflow_request=None, trigger_type=None):  # noqa: E501
        """HumanTaskTrigger - a model defined in Swagger"""  # noqa: E501
        self._start_workflow_request = None
        self._trigger_type = None
        self.discriminator = None
        if start_workflow_request is not None:
            self.start_workflow_request = start_workflow_request
        if trigger_type is not None:
            self.trigger_type = trigger_type

    @property
    def start_workflow_request(self):
        """Gets the start_workflow_request of this HumanTaskTrigger.  # noqa: E501


        :return: The start_workflow_request of this HumanTaskTrigger.  # noqa: E501
        :rtype: StartWorkflowRequest
        """
        return self._start_workflow_request

    @start_workflow_request.setter
    def start_workflow_request(self, start_workflow_request):
        """Sets the start_workflow_request of this HumanTaskTrigger.


        :param start_workflow_request: The start_workflow_request of this HumanTaskTrigger.  # noqa: E501
        :type: StartWorkflowRequest
        """

        self._start_workflow_request = start_workflow_request

    @property
    def trigger_type(self):
        """Gets the trigger_type of this HumanTaskTrigger.  # noqa: E501


        :return: The trigger_type of this HumanTaskTrigger.  # noqa: E501
        :rtype: str
        """
        return self._trigger_type

    @trigger_type.setter
    def trigger_type(self, trigger_type):
        """Sets the trigger_type of this HumanTaskTrigger.


        :param trigger_type: The trigger_type of this HumanTaskTrigger.  # noqa: E501
        :type: str
        """
        allowed_values = ["ASSIGNEE_CHANGED", "CLAIMANT_CHANGED", "PENDING", "IN_PROGRESS", "ASSIGNED", "COMPLETED", "TIMED_OUT"]  # noqa: E501
        if trigger_type not in allowed_values:
            raise ValueError(
                "Invalid value for `trigger_type` ({0}), must be one of {1}"  # noqa: E501
                .format(trigger_type, allowed_values)
            )

        self._trigger_type = trigger_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HumanTaskTrigger, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HumanTaskTrigger):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
