# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HumanTaskAssignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assignee': 'HumanTaskUser',
        'sla_minutes': 'int'
    }

    attribute_map = {
        'assignee': 'assignee',
        'sla_minutes': 'slaMinutes'
    }

    def __init__(self, assignee=None, sla_minutes=None):  # noqa: E501
        """HumanTaskAssignment - a model defined in Swagger"""  # noqa: E501
        self._assignee = None
        self._sla_minutes = None
        self.discriminator = None
        if assignee is not None:
            self.assignee = assignee
        if sla_minutes is not None:
            self.sla_minutes = sla_minutes

    @property
    def assignee(self):
        """Gets the assignee of this HumanTaskAssignment.  # noqa: E501


        :return: The assignee of this HumanTaskAssignment.  # noqa: E501
        :rtype: HumanTaskUser
        """
        return self._assignee

    @assignee.setter
    def assignee(self, assignee):
        """Sets the assignee of this HumanTaskAssignment.


        :param assignee: The assignee of this HumanTaskAssignment.  # noqa: E501
        :type: HumanTaskUser
        """

        self._assignee = assignee

    @property
    def sla_minutes(self):
        """Gets the sla_minutes of this HumanTaskAssignment.  # noqa: E501


        :return: The sla_minutes of this HumanTaskAssignment.  # noqa: E501
        :rtype: int
        """
        return self._sla_minutes

    @sla_minutes.setter
    def sla_minutes(self, sla_minutes):
        """Sets the sla_minutes of this HumanTaskAssignment.


        :param sla_minutes: The sla_minutes of this HumanTaskAssignment.  # noqa: E501
        :type: int
        """

        self._sla_minutes = sla_minutes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HumanTaskAssignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HumanTaskAssignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
