# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProtoRegistryEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'str',
        'filename': 'str',
        'service_name': 'str'
    }

    attribute_map = {
        'data': 'data',
        'filename': 'filename',
        'service_name': 'serviceName'
    }

    def __init__(self, data=None, filename=None, service_name=None):  # noqa: E501
        """ProtoRegistryEntry - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._filename = None
        self._service_name = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if filename is not None:
            self.filename = filename
        if service_name is not None:
            self.service_name = service_name

    @property
    def data(self):
        """Gets the data of this ProtoRegistryEntry.  # noqa: E501


        :return: The data of this ProtoRegistryEntry.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ProtoRegistryEntry.


        :param data: The data of this ProtoRegistryEntry.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def filename(self):
        """Gets the filename of this ProtoRegistryEntry.  # noqa: E501


        :return: The filename of this ProtoRegistryEntry.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this ProtoRegistryEntry.


        :param filename: The filename of this ProtoRegistryEntry.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def service_name(self):
        """Gets the service_name of this ProtoRegistryEntry.  # noqa: E501


        :return: The service_name of this ProtoRegistryEntry.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this ProtoRegistryEntry.


        :param service_name: The service_name of this ProtoRegistryEntry.  # noqa: E501
        :type: str
        """

        self._service_name = service_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProtoRegistryEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProtoRegistryEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
