# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SharedResourceModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_name': 'str',
        'resource_type': 'str',
        'shared_by': 'str',
        'shared_with': 'str'
    }

    attribute_map = {
        'resource_name': 'resourceName',
        'resource_type': 'resourceType',
        'shared_by': 'sharedBy',
        'shared_with': 'sharedWith'
    }

    def __init__(self, resource_name=None, resource_type=None, shared_by=None, shared_with=None):  # noqa: E501
        """SharedResourceModel - a model defined in Swagger"""  # noqa: E501
        self._resource_name = None
        self._resource_type = None
        self._shared_by = None
        self._shared_with = None
        self.discriminator = None
        if resource_name is not None:
            self.resource_name = resource_name
        if resource_type is not None:
            self.resource_type = resource_type
        if shared_by is not None:
            self.shared_by = shared_by
        if shared_with is not None:
            self.shared_with = shared_with

    @property
    def resource_name(self):
        """Gets the resource_name of this SharedResourceModel.  # noqa: E501


        :return: The resource_name of this SharedResourceModel.  # noqa: E501
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """Sets the resource_name of this SharedResourceModel.


        :param resource_name: The resource_name of this SharedResourceModel.  # noqa: E501
        :type: str
        """

        self._resource_name = resource_name

    @property
    def resource_type(self):
        """Gets the resource_type of this SharedResourceModel.  # noqa: E501


        :return: The resource_type of this SharedResourceModel.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this SharedResourceModel.


        :param resource_type: The resource_type of this SharedResourceModel.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def shared_by(self):
        """Gets the shared_by of this SharedResourceModel.  # noqa: E501


        :return: The shared_by of this SharedResourceModel.  # noqa: E501
        :rtype: str
        """
        return self._shared_by

    @shared_by.setter
    def shared_by(self, shared_by):
        """Sets the shared_by of this SharedResourceModel.


        :param shared_by: The shared_by of this SharedResourceModel.  # noqa: E501
        :type: str
        """

        self._shared_by = shared_by

    @property
    def shared_with(self):
        """Gets the shared_with of this SharedResourceModel.  # noqa: E501


        :return: The shared_with of this SharedResourceModel.  # noqa: E501
        :rtype: str
        """
        return self._shared_with

    @shared_with.setter
    def shared_with(self, shared_with):
        """Sets the shared_with of this SharedResourceModel.


        :param shared_with: The shared_with of this SharedResourceModel.  # noqa: E501
        :type: str
        """

        self._shared_with = shared_with

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SharedResourceModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedResourceModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
