# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TokenUsageLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api': 'str',
        'completion_tokens': 'int',
        'integration_name': 'str',
        'period_start': 'int',
        'prompt_tokens': 'int',
        'total_tokens': 'int'
    }

    attribute_map = {
        'api': 'api',
        'completion_tokens': 'completionTokens',
        'integration_name': 'integrationName',
        'period_start': 'periodStart',
        'prompt_tokens': 'promptTokens',
        'total_tokens': 'totalTokens'
    }

    def __init__(self, api=None, completion_tokens=None, integration_name=None, period_start=None, prompt_tokens=None, total_tokens=None):  # noqa: E501
        """TokenUsageLog - a model defined in Swagger"""  # noqa: E501
        self._api = None
        self._completion_tokens = None
        self._integration_name = None
        self._period_start = None
        self._prompt_tokens = None
        self._total_tokens = None
        self.discriminator = None
        if api is not None:
            self.api = api
        if completion_tokens is not None:
            self.completion_tokens = completion_tokens
        if integration_name is not None:
            self.integration_name = integration_name
        if period_start is not None:
            self.period_start = period_start
        if prompt_tokens is not None:
            self.prompt_tokens = prompt_tokens
        if total_tokens is not None:
            self.total_tokens = total_tokens

    @property
    def api(self):
        """Gets the api of this TokenUsageLog.  # noqa: E501


        :return: The api of this TokenUsageLog.  # noqa: E501
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """Sets the api of this TokenUsageLog.


        :param api: The api of this TokenUsageLog.  # noqa: E501
        :type: str
        """

        self._api = api

    @property
    def completion_tokens(self):
        """Gets the completion_tokens of this TokenUsageLog.  # noqa: E501


        :return: The completion_tokens of this TokenUsageLog.  # noqa: E501
        :rtype: int
        """
        return self._completion_tokens

    @completion_tokens.setter
    def completion_tokens(self, completion_tokens):
        """Sets the completion_tokens of this TokenUsageLog.


        :param completion_tokens: The completion_tokens of this TokenUsageLog.  # noqa: E501
        :type: int
        """

        self._completion_tokens = completion_tokens

    @property
    def integration_name(self):
        """Gets the integration_name of this TokenUsageLog.  # noqa: E501


        :return: The integration_name of this TokenUsageLog.  # noqa: E501
        :rtype: str
        """
        return self._integration_name

    @integration_name.setter
    def integration_name(self, integration_name):
        """Sets the integration_name of this TokenUsageLog.


        :param integration_name: The integration_name of this TokenUsageLog.  # noqa: E501
        :type: str
        """

        self._integration_name = integration_name

    @property
    def period_start(self):
        """Gets the period_start of this TokenUsageLog.  # noqa: E501


        :return: The period_start of this TokenUsageLog.  # noqa: E501
        :rtype: int
        """
        return self._period_start

    @period_start.setter
    def period_start(self, period_start):
        """Sets the period_start of this TokenUsageLog.


        :param period_start: The period_start of this TokenUsageLog.  # noqa: E501
        :type: int
        """

        self._period_start = period_start

    @property
    def prompt_tokens(self):
        """Gets the prompt_tokens of this TokenUsageLog.  # noqa: E501


        :return: The prompt_tokens of this TokenUsageLog.  # noqa: E501
        :rtype: int
        """
        return self._prompt_tokens

    @prompt_tokens.setter
    def prompt_tokens(self, prompt_tokens):
        """Sets the prompt_tokens of this TokenUsageLog.


        :param prompt_tokens: The prompt_tokens of this TokenUsageLog.  # noqa: E501
        :type: int
        """

        self._prompt_tokens = prompt_tokens

    @property
    def total_tokens(self):
        """Gets the total_tokens of this TokenUsageLog.  # noqa: E501


        :return: The total_tokens of this TokenUsageLog.  # noqa: E501
        :rtype: int
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this TokenUsageLog.


        :param total_tokens: The total_tokens of this TokenUsageLog.  # noqa: E501
        :type: int
        """

        self._total_tokens = total_tokens

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenUsageLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenUsageLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
