from enum import Enum


class MetricDocumentation(str, Enum):
    API_REQUEST_TIME = "HTTP API client request latency in seconds"
    EXTERNAL_PAYLOAD_USED = "Incremented each time external payload storage is used"
    TASK_ACK_ERROR = "Task ack has encountered an exception"
    TASK_ACK_FAILED = "Task ack failed"
    TASK_EXECUTE_ERROR = "Execution error"
    TASK_EXECUTE_TIME = "Time to execute a task (last-value gauge; see task_execute_time_seconds for histogram)"
    TASK_EXECUTE_TIME_HISTOGRAM = "Task execution latency in seconds"
    TASK_EXECUTION_QUEUE_FULL = "Counter to record execution queue has saturated"
    TASK_EXECUTION_STARTED = "Incremented each time a polled task is dispatched to the worker function"
    TASK_PAUSED = "Counter for number of times the task has been polled, when the worker has been paused"
    TASK_POLL = "Incremented each time polling is done"
    TASK_POLL_ERROR = "Client error when polling for a task queue"
    TASK_POLL_TIME = "Time to poll for a batch of tasks (last-value gauge; see task_poll_time_seconds for histogram)"
    TASK_POLL_TIME_HISTOGRAM = "Task poll latency in seconds"
    TASK_RESULT_SIZE = "Records output payload size of a task (last-value gauge; see task_result_size_bytes for canonical name)"
    TASK_RESULT_SIZE_BYTES = "Records output payload size of a task in bytes"
    TASK_UPDATE_ERROR = "Task status cannot be updated back to server"
    TASK_UPDATE_TIME_HISTOGRAM = "Task update latency in seconds"
    THREAD_UNCAUGHT_EXCEPTION = "Uncaught exceptions raised by worker threads"
    WORKER_RESTART = "Worker subprocess restarted"
    WORKFLOW_START_ERROR = "Counter for workflow start errors"
    WORKFLOW_INPUT_SIZE = "Records input payload size of a workflow (last-value gauge; see workflow_input_size_bytes for canonical name)"
    WORKFLOW_INPUT_SIZE_BYTES = "Records input payload size of a workflow in bytes"
