# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SharingResourceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_shared_resources(self, **kwargs):  # noqa: E501
        """get_shared_resources  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_shared_resources(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[SharedResourceModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_shared_resources_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_shared_resources_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_shared_resources_with_http_info(self, **kwargs):  # noqa: E501
        """get_shared_resources  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_shared_resources_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[SharedResourceModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_shared_resources" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/api/share/getSharedResources', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SharedResourceModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_sharing_resource(self, resource_type, resource_name, shared_with, **kwargs):  # noqa: E501
        """remove_sharing_resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_sharing_resource(resource_type, resource_name, shared_with, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str resource_type: (required)
        :param str resource_name: (required)
        :param str shared_with: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remove_sharing_resource_with_http_info(resource_type, resource_name, shared_with, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_sharing_resource_with_http_info(resource_type, resource_name, shared_with, **kwargs)  # noqa: E501
            return data

    def remove_sharing_resource_with_http_info(self, resource_type, resource_name, shared_with, **kwargs):  # noqa: E501
        """remove_sharing_resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_sharing_resource_with_http_info(resource_type, resource_name, shared_with, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str resource_type: (required)
        :param str resource_name: (required)
        :param str shared_with: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['resource_type', 'resource_name', 'shared_with']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_sharing_resource" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'resource_type' is set
        if ('resource_type' not in params or
                params['resource_type'] is None):
            raise ValueError("Missing the required parameter `resource_type` when calling `remove_sharing_resource`")  # noqa: E501
        # verify the required parameter 'resource_name' is set
        if ('resource_name' not in params or
                params['resource_name'] is None):
            raise ValueError("Missing the required parameter `resource_name` when calling `remove_sharing_resource`")  # noqa: E501
        # verify the required parameter 'shared_with' is set
        if ('shared_with' not in params or
                params['shared_with'] is None):
            raise ValueError("Missing the required parameter `shared_with` when calling `remove_sharing_resource`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'resource_type' in params:
            query_params.append(('resourceType', params['resource_type']))  # noqa: E501
        if 'resource_name' in params:
            query_params.append(('resourceName', params['resource_name']))  # noqa: E501
        if 'shared_with' in params:
            query_params.append(('sharedWith', params['shared_with']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/api/share/removeSharingResource', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def share_resource(self, resource_type, resource_name, shared_with, **kwargs):  # noqa: E501
        """share_resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.share_resource(resource_type, resource_name, shared_with, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str resource_type: (required)
        :param str resource_name: (required)
        :param str shared_with: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.share_resource_with_http_info(resource_type, resource_name, shared_with, **kwargs)  # noqa: E501
        else:
            (data) = self.share_resource_with_http_info(resource_type, resource_name, shared_with, **kwargs)  # noqa: E501
            return data

    def share_resource_with_http_info(self, resource_type, resource_name, shared_with, **kwargs):  # noqa: E501
        """share_resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.share_resource_with_http_info(resource_type, resource_name, shared_with, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str resource_type: (required)
        :param str resource_name: (required)
        :param str shared_with: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['resource_type', 'resource_name', 'shared_with']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method share_resource" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'resource_type' is set
        if ('resource_type' not in params or
                params['resource_type'] is None):
            raise ValueError("Missing the required parameter `resource_type` when calling `share_resource`")  # noqa: E501
        # verify the required parameter 'resource_name' is set
        if ('resource_name' not in params or
                params['resource_name'] is None):
            raise ValueError("Missing the required parameter `resource_name` when calling `share_resource`")  # noqa: E501
        # verify the required parameter 'shared_with' is set
        if ('shared_with' not in params or
                params['shared_with'] is None):
            raise ValueError("Missing the required parameter `shared_with` when calling `share_resource`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'resource_type' in params:
            query_params.append(('resourceType', params['resource_type']))  # noqa: E501
        if 'resource_name' in params:
            query_params.append(('resourceName', params['resource_name']))  # noqa: E501
        if 'shared_with' in params:
            query_params.append(('sharedWith', params['shared_with']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/api/share/shareResource', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
