"""Cross-validation: SDK worker names must match server-compiled task names.

These tests verify that the task names generated by the Python SDK
(_collect_worker_names) match what the server compiler would produce.
A mismatch means workers register for task names that never appear in
the compiled workflow, causing tasks to hang forever with no worker.
"""
import pytest
from unittest.mock import MagicMock


class TestSwarmTransferWorkerNames:
    """Transfer worker names must use the SOURCE agent name as prefix."""

    def test_transfer_names_use_source_not_parent(self):
        """coder_transfer_to_qa_tester, NOT coding_qa_transfer_to_qa_tester."""
        from conductor.ai.agents import Agent, Strategy
        from conductor.ai.agents.handoff import OnTextMention

        coder = Agent(name="coder", model="openai/gpt-4o")
        qa = Agent(name="qa_tester", model="openai/gpt-4o")
        swarm = Agent(
            name="coding_qa",
            model="openai/gpt-4o",
            agents=[coder, qa],
            strategy=Strategy.SWARM,
            handoffs=[
                OnTextMention(text="HANDOFF_TO_QA", target="qa_tester"),
                OnTextMention(text="HANDOFF_TO_CODER", target="coder"),
            ],
        )

        from conductor.ai.agents.runtime.runtime import AgentRuntime

        runtime = AgentRuntime.__new__(AgentRuntime)
        names = runtime._collect_worker_names(swarm)

        # Source-prefixed transfer names (matching server compiler)
        assert "coder_transfer_to_qa_tester" in names
        assert "qa_tester_transfer_to_coder" in names
        assert "coder_transfer_to_coding_qa" in names
        assert "coding_qa_transfer_to_coder" in names
        assert "coding_qa_transfer_to_qa_tester" in names
        assert "qa_tester_transfer_to_coding_qa" in names

        # MUST NOT use parent-only prefix
        # This was the bug: all names were coding_qa_transfer_to_*
        # which didn't match server's coder_transfer_to_qa_tester
        transfer_names = [n for n in names if "_transfer_to_" in n]
        parent_only = [n for n in transfer_names if n.startswith("coding_qa_transfer_to_")]
        non_parent = [n for n in transfer_names if not n.startswith("coding_qa_transfer_to_")]
        # Both parent AND sub-agent prefixed names must exist
        assert len(parent_only) > 0, "Parent agent should also have transfer tools"
        assert len(non_parent) > 0, "Sub-agents must have their own transfer tools"


class TestCliToolNamePrefixing:
    """CLI and code execution tools must be prefixed with agent name."""

    def test_run_command_prefixed_per_agent(self):
        from conductor.ai.agents import Agent

        a = Agent(name="fetcher", model="openai/gpt-4o", cli_commands=True, cli_allowed_commands=["gh", "git"])
        b = Agent(name="pusher", model="openai/gpt-4o", cli_commands=True, cli_allowed_commands=["gh"])

        a_tools = [t._tool_def.name for t in a.tools if hasattr(t, "_tool_def")]
        b_tools = [t._tool_def.name for t in b.tools if hasattr(t, "_tool_def")]

        assert "fetcher_run_command" in a_tools
        assert "pusher_run_command" in b_tools
        # No collision
        assert a_tools != b_tools

    def test_execute_code_prefixed_per_agent(self):
        from conductor.ai.agents import Agent

        a = Agent(name="coder", model="openai/gpt-4o", local_code_execution=True)
        b = Agent(name="tester", model="openai/gpt-4o", local_code_execution=True)

        a_tools = [t._tool_def.name for t in a.tools if hasattr(t, "_tool_def")]
        b_tools = [t._tool_def.name for t in b.tools if hasattr(t, "_tool_def")]

        assert "coder_execute_code" in a_tools
        assert "tester_execute_code" in b_tools
        assert a_tools != b_tools

    def test_sub_agents_get_own_prefixed_tools(self):
        """Sub-agents in a pipeline each get their own prefixed CLI tool."""
        from conductor.ai.agents import Agent

        fetcher = Agent(
            name="git_fetch",
            model="openai/gpt-4o",
            cli_commands=True,
            cli_allowed_commands=["gh", "git", "mktemp"],
        )
        pusher = Agent(
            name="git_push",
            model="openai/gpt-4o",
            cli_commands=True,
            cli_allowed_commands=["gh"],
        )

        pipeline = fetcher >> pusher

        all_tools = {}
        for sub in [fetcher, pusher]:
            for t in sub.tools:
                if hasattr(t, "_tool_def"):
                    all_tools[t._tool_def.name] = sub.name

        assert "git_fetch_run_command" in all_tools
        assert "git_push_run_command" in all_tools
        assert all_tools["git_fetch_run_command"] == "git_fetch"
        assert all_tools["git_push_run_command"] == "git_push"


class TestSystemWorkerNamePrefixing:
    """All system worker names must be prefixed with agent name."""

    def test_all_system_workers_prefixed(self):
        from conductor.ai.agents import Agent
        from conductor.ai.agents.runtime.runtime import AgentRuntime
        from conductor.ai.agents.handoff import OnTextMention

        agent = Agent(
            name="my_agent",
            model="openai/gpt-4o",
            instructions="test",
            max_turns=10,
            termination=lambda result, iteration: False,
        )

        runtime = AgentRuntime.__new__(AgentRuntime)
        names = runtime._collect_worker_names(agent)

        system_names = [n for n in names if n != "my_agent" and not n.startswith("my_agent")]
        assert len(system_names) == 0, (
            f"System worker names without agent prefix: {system_names}. "
            "All system workers must start with the agent name."
        )
