# Copyright (c) 2025 Agentspan
# Licensed under the MIT License. See LICENSE file in the project root for details.

"""Tests for _normalize_handoff_target in runtime.py."""

from conductor.ai.agents.runtime.runtime import _normalize_handoff_target


class TestNormalizeHandoffTarget:
    """Verify that Conductor sub-workflow references are normalized to agent names.

    Patterns generated by MultiAgentCompiler:
      - handoff/router: {parent}_handoff_{idx}_{child}
      - sequential:     {parent}_step_{idx}_{child}
      - parallel:       {parent}_parallel_{idx}_{child}
      - round_robin:    {parent}_agent_{idx}_{child}
      - swarm:          {parent}_agent_{idx}_{child}
    """

    def test_already_clean(self):
        assert _normalize_handoff_target("billing") == "billing"

    def test_strip_turn_counter(self):
        assert _normalize_handoff_target("billing__1") == "billing"
        assert _normalize_handoff_target("billing__42") == "billing"

    def test_indexed_prefix(self):
        """Fallback: Conductor indexes sub-workflows like 0_billing."""
        assert _normalize_handoff_target("0_billing") == "billing"
        assert _normalize_handoff_target("1_weather") == "weather"

    def test_indexed_prefix_with_turn(self):
        assert _normalize_handoff_target("0_billing__1") == "billing"
        assert _normalize_handoff_target("1_weather__3") == "weather"

    # ── Handoff / Router strategy ──────────────────────────────────────

    def test_handoff_pattern(self):
        """Handoff strategy: {parent}_handoff_{idx}_{child}."""
        assert _normalize_handoff_target("support_handoff_0_billing") == "billing"
        assert _normalize_handoff_target("support_handoff_1_weather") == "weather"

    def test_handoff_with_turn_counter(self):
        assert _normalize_handoff_target("support_handoff_0_billing__2") == "billing"

    def test_router_uses_handoff_pattern(self):
        assert _normalize_handoff_target("dev_team_handoff_0_coder") == "coder"
        assert _normalize_handoff_target("dev_team_handoff_1_calculator") == "calculator"

    # ── Sequential strategy ────────────────────────────────────────────

    def test_sequential_step_pattern(self):
        """Sequential: {parent}_step_{idx}_{child}."""
        assert _normalize_handoff_target("pipeline_step_0_researcher") == "researcher"
        assert _normalize_handoff_target("pipeline_step_1_writer") == "writer"

    def test_sequential_compound_parent(self):
        assert _normalize_handoff_target("researcher_writer_step_0_researcher") == "researcher"
        assert _normalize_handoff_target("researcher_writer_step_1_writer") == "writer"

    # ── Parallel strategy ──────────────────────────────────────────────

    def test_parallel_pattern(self):
        """Parallel: {parent}_parallel_{idx}_{child}."""
        assert _normalize_handoff_target("analysis_parallel_0_pros_analyst") == "pros_analyst"
        assert _normalize_handoff_target("analysis_parallel_1_cons_analyst") == "cons_analyst"

    # ── Round-robin strategy ───────────────────────────────────────────

    def test_round_robin_agent_pattern(self):
        """Round-robin: {parent}_agent_{idx}_{child}."""
        assert _normalize_handoff_target("debate_agent_0_optimist") == "optimist"
        assert _normalize_handoff_target("debate_agent_1_pessimist") == "pessimist"

    def test_round_robin_with_turn_counter(self):
        assert _normalize_handoff_target("debate_agent_0_optimist__1") == "optimist"
        assert _normalize_handoff_target("debate_agent_1_pessimist__3") == "pessimist"

    # ── Swarm strategy ─────────────────────────────────────────────────

    def test_swarm_agent_pattern(self):
        """Swarm: {parent}_agent_{idx}_{child}."""
        assert _normalize_handoff_target("support_agent_0_billing") == "billing"
        assert _normalize_handoff_target("support_agent_1_tech") == "tech"

    def test_swarm_with_turn_counter(self):
        assert _normalize_handoff_target("support_agent_1_tech__2") == "tech"

    # ── Compound agent names ───────────────────────────────────────────

    def test_compound_agent_name_preserved(self):
        """Agent names with underscores should be preserved."""
        assert _normalize_handoff_target("analysis_parallel_0_pros_analyst") == "pros_analyst"
        assert _normalize_handoff_target("team_agent_0_order_handler") == "order_handler"
        assert _normalize_handoff_target("0_order_handler") == "order_handler"
        assert _normalize_handoff_target("0_order_handler__1") == "order_handler"
