# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HumanTaskUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'str',
        'user_type': 'str'
    }

    attribute_map = {
        'user': 'user',
        'user_type': 'userType'
    }

    def __init__(self, user=None, user_type=None):  # noqa: E501
        """HumanTaskUser - a model defined in Swagger"""  # noqa: E501
        self._user = None
        self._user_type = None
        self.discriminator = None
        if user is not None:
            self.user = user
        if user_type is not None:
            self.user_type = user_type

    @property
    def user(self):
        """Gets the user of this HumanTaskUser.  # noqa: E501


        :return: The user of this HumanTaskUser.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this HumanTaskUser.


        :param user: The user of this HumanTaskUser.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def user_type(self):
        """Gets the user_type of this HumanTaskUser.  # noqa: E501


        :return: The user_type of this HumanTaskUser.  # noqa: E501
        :rtype: str
        """
        return self._user_type

    @user_type.setter
    def user_type(self, user_type):
        """Sets the user_type of this HumanTaskUser.


        :param user_type: The user_type of this HumanTaskUser.  # noqa: E501
        :type: str
        """
        allowed_values = ["EXTERNAL_USER", "EXTERNAL_GROUP", "CONDUCTOR_USER", "CONDUCTOR_GROUP"]  # noqa: E501
        if user_type not in allowed_values:
            raise ValueError(
                "Invalid value for `user_type` ({0}), must be one of {1}"  # noqa: E501
                .format(user_type, allowed_values)
            )

        self._user_type = user_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HumanTaskUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HumanTaskUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
