# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HumanTaskTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_time': 'int',
        'created_by': 'str',
        'json_schema': 'dict(str, object)',
        'name': 'str',
        'owner_app': 'str',
        'tags': 'list[Tag]',
        'template_ui': 'dict(str, object)',
        'update_time': 'int',
        'updated_by': 'str',
        'version': 'int'
    }

    attribute_map = {
        'create_time': 'createTime',
        'created_by': 'createdBy',
        'json_schema': 'jsonSchema',
        'name': 'name',
        'owner_app': 'ownerApp',
        'tags': 'tags',
        'template_ui': 'templateUI',
        'update_time': 'updateTime',
        'updated_by': 'updatedBy',
        'version': 'version'
    }

    def __init__(self, create_time=None, created_by=None, json_schema=None, name=None, owner_app=None, tags=None, template_ui=None, update_time=None, updated_by=None, version=None):  # noqa: E501
        """HumanTaskTemplate - a model defined in Swagger"""  # noqa: E501
        self._create_time = None
        self._created_by = None
        self._json_schema = None
        self._name = None
        self._owner_app = None
        self._tags = None
        self._template_ui = None
        self._update_time = None
        self._updated_by = None
        self._version = None
        self.discriminator = None
        if create_time is not None:
            self.create_time = create_time
        if created_by is not None:
            self.created_by = created_by
        self.json_schema = json_schema
        self.name = name
        if owner_app is not None:
            self.owner_app = owner_app
        if tags is not None:
            self.tags = tags
        self.template_ui = template_ui
        if update_time is not None:
            self.update_time = update_time
        if updated_by is not None:
            self.updated_by = updated_by
        self.version = version

    @property
    def create_time(self):
        """Gets the create_time of this HumanTaskTemplate.  # noqa: E501


        :return: The create_time of this HumanTaskTemplate.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this HumanTaskTemplate.


        :param create_time: The create_time of this HumanTaskTemplate.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def created_by(self):
        """Gets the created_by of this HumanTaskTemplate.  # noqa: E501


        :return: The created_by of this HumanTaskTemplate.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this HumanTaskTemplate.


        :param created_by: The created_by of this HumanTaskTemplate.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def json_schema(self):
        """Gets the json_schema of this HumanTaskTemplate.  # noqa: E501


        :return: The json_schema of this HumanTaskTemplate.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._json_schema

    @json_schema.setter
    def json_schema(self, json_schema):
        """Sets the json_schema of this HumanTaskTemplate.


        :param json_schema: The json_schema of this HumanTaskTemplate.  # noqa: E501
        :type: dict(str, object)
        """
        if json_schema is None:
            raise ValueError("Invalid value for `json_schema`, must not be `None`")  # noqa: E501

        self._json_schema = json_schema

    @property
    def name(self):
        """Gets the name of this HumanTaskTemplate.  # noqa: E501


        :return: The name of this HumanTaskTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HumanTaskTemplate.


        :param name: The name of this HumanTaskTemplate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def owner_app(self):
        """Gets the owner_app of this HumanTaskTemplate.  # noqa: E501


        :return: The owner_app of this HumanTaskTemplate.  # noqa: E501
        :rtype: str
        """
        return self._owner_app

    @owner_app.setter
    def owner_app(self, owner_app):
        """Sets the owner_app of this HumanTaskTemplate.


        :param owner_app: The owner_app of this HumanTaskTemplate.  # noqa: E501
        :type: str
        """

        self._owner_app = owner_app

    @property
    def tags(self):
        """Gets the tags of this HumanTaskTemplate.  # noqa: E501


        :return: The tags of this HumanTaskTemplate.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this HumanTaskTemplate.


        :param tags: The tags of this HumanTaskTemplate.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def template_ui(self):
        """Gets the template_ui of this HumanTaskTemplate.  # noqa: E501


        :return: The template_ui of this HumanTaskTemplate.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._template_ui

    @template_ui.setter
    def template_ui(self, template_ui):
        """Sets the template_ui of this HumanTaskTemplate.


        :param template_ui: The template_ui of this HumanTaskTemplate.  # noqa: E501
        :type: dict(str, object)
        """
        if template_ui is None:
            raise ValueError("Invalid value for `template_ui`, must not be `None`")  # noqa: E501

        self._template_ui = template_ui

    @property
    def update_time(self):
        """Gets the update_time of this HumanTaskTemplate.  # noqa: E501


        :return: The update_time of this HumanTaskTemplate.  # noqa: E501
        :rtype: int
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this HumanTaskTemplate.


        :param update_time: The update_time of this HumanTaskTemplate.  # noqa: E501
        :type: int
        """

        self._update_time = update_time

    @property
    def updated_by(self):
        """Gets the updated_by of this HumanTaskTemplate.  # noqa: E501


        :return: The updated_by of this HumanTaskTemplate.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this HumanTaskTemplate.


        :param updated_by: The updated_by of this HumanTaskTemplate.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def version(self):
        """Gets the version of this HumanTaskTemplate.  # noqa: E501


        :return: The version of this HumanTaskTemplate.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this HumanTaskTemplate.


        :param version: The version of this HumanTaskTemplate.  # noqa: E501
        :type: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HumanTaskTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HumanTaskTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
