# coding: utf-8

"""
    Orkes Conductor API Server

    Orkes Conductor API Server  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestParam(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'required': 'bool',
        'schema': 'Schema',
        'type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'required': 'required',
        'schema': 'schema',
        'type': 'type'
    }

    def __init__(self, name=None, required=None, schema=None, type=None):  # noqa: E501
        """RequestParam - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._required = None
        self._schema = None
        self._type = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if required is not None:
            self.required = required
        if schema is not None:
            self.schema = schema
        if type is not None:
            self.type = type

    @property
    def name(self):
        """Gets the name of this RequestParam.  # noqa: E501


        :return: The name of this RequestParam.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RequestParam.


        :param name: The name of this RequestParam.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def required(self):
        """Gets the required of this RequestParam.  # noqa: E501


        :return: The required of this RequestParam.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this RequestParam.


        :param required: The required of this RequestParam.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def schema(self):
        """Gets the schema of this RequestParam.  # noqa: E501


        :return: The schema of this RequestParam.  # noqa: E501
        :rtype: Schema
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this RequestParam.


        :param schema: The schema of this RequestParam.  # noqa: E501
        :type: Schema
        """

        self._schema = schema

    @property
    def type(self):
        """Gets the type of this RequestParam.  # noqa: E501


        :return: The type of this RequestParam.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RequestParam.


        :param type: The type of this RequestParam.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestParam, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestParam):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
