name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  publish-release-at-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        run: >
          DOCKER_BUILDKIT=1 docker build
          --progress=plain
          --build-arg CONDUCTOR_PYTHON_VERSION=${{ github.ref_name }}
          --build-arg PYPI_USER=${{ secrets.pypi_user }}
          --build-arg PYPI_PASS=${{ secrets.pypi_pass }}
          --target=publish
          .
